name: Update Funding History

on:
  push:                  # <--- NOUVEAU : Lance le script dÃ¨s qu'on push !
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *' # On garde le programmateur pour plus tard
  workflow_dispatch:     # On garde le bouton manuel
  
jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Autorise le bot Ã  sauvegarder le fichier

    steps:
      - name: RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installation des dÃ©pendances
        run: pip install -r requirements.txt

      - name: ExÃ©cution du Recorder
        env:
          EXT_API_KEY: ${{ secrets.EXT_API_KEY }}
          PACIFICA_API_KEY: ${{ secrets.PACIFICA_API_KEY }}
        run: python recorder.py

      - name: Sauvegarde (Commit & Push)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Auto-update funding history"
          file_pattern: "funding_history.parquet"
