name: Update Funding History

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/30 * * * *'  # <-- On tente toutes les 30 minutes
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Donne le droit au robot de sauvegarder le fichier parquet

    steps:
      - name: RÃ©cupÃ©ration du code
        uses: actions/checkout@v4

      - name: Installation de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Installation des librairies
        run: pip install -r requirements.txt

      - name: Lancement du Recorder
        env:
          # On injecte les clÃ©s secrÃ¨tes ici
          EXT_API_KEY: ${{ secrets.EXT_API_KEY }}
          PACIFICA_API_KEY: ${{ secrets.PACIFICA_API_KEY }}
        run: python recorder.py

      - name: Sauvegarde et Push (Commit)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ðŸ¤– Auto-update funding history"
          file_pattern: "funding_history.parquet"
